POST http://localhost:4000/login
Content-Type: application/json


{
 "email": "Jaydon@gmail.com",
 "password": "1455"
}

### 
GET http://localhost:4000/me
Content-Type: application/json

### 

DELETE http://localhost:4000/logout
Content-Type: application/json

